image: registry.freedesktop.org/pipewire/pipewire/fedora:31

variables:
  DEPENDENCIES: gtk-doc gobject-introspection-devel

build:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
    - git clone https://gitlab.freedesktop.org/pipewire/pipewire.git
  script:
    # Build pipewire
    - cd pipewire
    - meson . _build --prefix=/usr
        -Dpipewire-alsa=false -Dpipewire-pulseaudio=false -Dpipewire-jack=false
        -Djack=false -Dvulkan=false -Dgstreamer=false -Dbluez5=false -Dman=false
        -Dvideotestsrc=true -Daudiotestsrc=true
    - ninja -C _build
    - ninja -C _build install
    - cd ..
    # Build wireplumber
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
